# Generated by Django 2.2.1 on 2019-07-14 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUsers', '0002_auto_20190714_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Biology',
            field=models.ManyToManyField(blank=True, related_name='user', to='statistic.biology', verbose_name='b'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Math',
            field=models.ManyToManyField(blank=True, related_name='user', to='statistic.math', verbose_name='m'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Phisycs',
            field=models.ManyToManyField(blank=True, related_name='user', to='statistic.phisycs', verbose_name='p'),
        ),
    ]
